sessions:
  max:
    exchange: &exchange max
    envVarPrefix: max
    publicOnly: true

exchangeStrategies:
- on: *exchange
  sentinel:
    symbol: BTCUSDT
    interval: 1m
    scoreThreshold: 0.7
    klineLimit: 43200
    window: 1440
