sessions:
  max:
    exchange: &exchange max
    envVarPrefix: max
    publicOnly: true

exchangeStrategies:
  - on: *exchange
    sentinel:
      symbol: BTCUSDT
      interval: &intervel 1m
      threshold: &threshold 0.7
      proportion: &proportion 0.05
      numSamples: &numSamples 1440
      window: &window 60
  - on: *exchange
    sentinel:
      symbol: ETHUSDT
      interval: *intervel
      threshold: *threshold
      proportion: *proportion
      numSamples: *numSamples
      window: *window
  - on: *exchange
    sentinel:
      symbol: BCHUSDT
      interval: *intervel
      threshold: *threshold
      proportion: *proportion
      numSamples: *numSamples
      window: *window
  - on: *exchange
    sentinel:
      symbol: LTCUSDT
      interval: *intervel
      threshold: *threshold
      proportion: *proportion
      numSamples: *numSamples
      window: *window
  - on: *exchange
    sentinel:
      symbol: XRPUSDT
      interval: *intervel
      threshold: *threshold
      proportion: *proportion
      numSamples: *numSamples
      window: *window
  - on: *exchange
    sentinel:
      symbol: MAXUSDT
      interval: *intervel
      threshold: *threshold
      proportion: *proportion
      numSamples: *numSamples
      window: *window
  - on: *exchange
    sentinel:
      symbol: BCNTUSDT
      interval: *intervel
      threshold: *threshold
      proportion: *proportion
      numSamples: *numSamples
      window: *window
  - on: *exchange
    sentinel:
      symbol: ARBUSDT
      interval: *intervel
      threshold: *threshold
      proportion: *proportion
      numSamples: *numSamples
      window: *window