---
sessions:
  binance:
    exchange: binance
    futures: true
    symbolLeverage:
      BTCUSDT: 3
      ETHUSDT: 3

exchangeStrategies:
  - on: binance
    tradingdesk:
      maxLossLimit: 10
      openPositions:
      - symbol: BTCUSDT
        side: SELL
        quantity: 0.001
        stopLossPrice: 110_000
        takeProfitPrice: 105_000
      closePositionsOnShutdown: true